### ISSUE TITLE
Avoid static methods in CartOps & ProductOps

### ISSUE THREAD

**Issue by LavishSwarnkar** [imAtulSharma/MyEcomConsole#3]
https://github.com/imAtulSharma/MyEcom/blob/e0d2edf2e7bb5837475f68db3d8fb5e5cc06b804/src/com/streamliners/models/CartOperations.java#L18

You are passing hashmap & cart again and again in all methods, instead remove static ; pass it once and call methods directly.

**Comment by imAtulSharma** [comment]
DONE!
